---
title: "Gentrification Final"
author: "Aran Ansari"
date: "April 30, 2019"
output: html_document
runtime: shiny
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tmap)    # for static and interactive maps
library(leaflet) # for interactive maps
library(mapview) # for interactive maps
library(ggiraph)
library(sf)
library(geojsonR)
library(sp)
library(geojsonio)
library(ggmap)
library(dplyr)
library(shiny)
library(shinydashboard)
library(rsconnect)
rsconnect::setAccountInfo(name='aranansari',
                          token='44DFE0D9A8F8E02520CB39D8D488D553',
                          secret='/0IoCo5c6e7Ss/hVrND3VFQwItx15fNX7Vt74FeM')
```


Below is my project presentation: 

```{r, echo=FALSE}
#Read in master data
gentrification.df <- read.csv(file.choose(new = FALSE))


#Read in JSON file that includes the polygonal shapes of the neighborhoods
NYC.js <- geojson_read(file.choose(new = FALSE),what="sp")
#Test if it prints the outlines
colnames(NYC.js@data)[colnames(NYC.js@data)=="ntacode"] <- "GeoID"

NYC.js@data$id <- seq(0,194,by=1)
NYC.js@data <- merge(NYC.js@data,gentrification.df,by="GeoID",all=TRUE)
#add an id column for merging purposes

#Fortify and merge the two data sets
NYC.js.f <- fortify(NYC.js)
NYC.js.f <- merge(NYC.js.f,NYC.js@data,by="id",all=TRUE)



#GOOGLE Maps requires API key
register_google(key = "AIzaSyCB3s03JVUmb_cpbhWrt_BF52hWwxnHXT8", write = TRUE)

#Use data to layer outline over real NYC map (ggmap). Using GFactor2010 as fill
#2010
Outline10  <- geom_polygon_interactive(aes(long,lat,group=group,fill=GFactor2010,tooltip=sprintf("%s<br>%s",GeogName,GFactor2010)),data=subset(NYC.js.f,lat >=-60 & lat <= 90),colour = "black")
mapImage <- ggmap(get_googlemap(c(lon=-74.0060,lat=40.7128),scale=1,zoom=10),fullpage=TRUE,extent = "panel")
NYCMAP2010   <- mapImage+Outline10+labs(title = 'Gentrification by Neighborhood',subtitle = 'Based on 2010 Census Data')

Outline16  <- geom_polygon_interactive(aes(long,lat,group=group,fill=GFactor2016,tooltip=sprintf("%s<br>%s",GeogName,GFactor2016)),data=subset(NYC.js.f,lat >=-60 & lat <= 90),colour = "black")
mapImage <- ggmap(get_googlemap(c(lon=-74.0060,lat=40.7128),scale=1,zoom=10),fullpage=TRUE,extent = "panel")
NYCMAP2016   <- mapImage+Outline16+labs(title = 'Gentrification by Neighborhood',subtitle = 'Based on 2016 Census Data')

OutlineChange  <- geom_polygon_interactive(aes(long,lat,group=group,fill=GFactorChange,tooltip=sprintf("%s<br>%s",GeogName,GFactorChange)),data=subset(NYC.js.f,lat >=-60 & lat <= 90),colour = "black")
mapImage <- ggmap(get_googlemap(c(lon=-74.0060,lat=40.7128),scale=1,zoom=10),fullpage=TRUE,extent = "panel")
NYCMAPCHANGE   <- mapImage+OutlineChange+scale_fill_gradient(low = "#000000", high = "#ffff00")+labs(title = 'Gentrification by Neighborhood',subtitle = 'Based on 2010-16 Census Data')


```

## Gentrification Application

Below is the shiny application I've embedded with multiple graphs and maps showing Gentrification and other variables by neighborhood.Enjoy!

```{r, echo=FALSE}

ui <- navbarPage("Gentrification in New York City",
    # Boxes need to be put in a row (or column)
      
      tabPanel("2010", mainPanel(girafeOutput("plot2"))),
    
      tabPanel("2016", mainPanel(girafeOutput("plot3"))),

      tabPanel("Change over Time", mainPanel(girafeOutput("plot4"))),
      
    tabPanel("Interactive Map",
    mainPanel(selectInput("variable","Variable:",choices = colnames(gentrification.df[-1:-3])),
      mainPanel(girafeOutput("plot5"))))
    
  
)

server <- function(input, output) {
  
  output$plot2 <- renderGirafe({
    girafe(code=print(NYCMAP2010))
  })
  
  output$plot3 <- renderGirafe({
    girafe(code=print(NYCMAP2016))
  })
  
  output$plot4 <- renderGirafe({
    girafe(code=print(NYCMAPCHANGE))
  })
  
  
  output$plot5 <- renderGirafe({
    girafe(code=print(mapImage+geom_polygon_interactive(aes(long,lat,group=group,fill=NYC.js.f[,input$variable],tooltip=sprintf("%s<br>%s",NYC.js.f$GeogName,NYC.js.f[,input$variable])),data=NYC.js.f,colour = "black")+scale_fill_gradient(low = "#ffffff", high = "#FF0000")))
  })
  
  }

shinyApp(ui, server)



```

